stages:
  - image

build_image:
  stage: image
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
  script:
    - docker build -t $CI_REGISTRY$CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY$CI_REGISTRY_IMAGE
    #- docker-compose up
